# Nomes das tabelas no Hive Metastore
tabelas:
  faturamento: bol.faturamento_centros_bol
  produtos: bol.produtos_site
  clientes: bol.tb_dados_clientes # Tabela de clientes atualizada

# Parâmetros para o modelo de IA (FP-Growth)
modelo_ia:
  min_support: 0.001
  min_confidence: 0.05

# Parâmetros de filtro de negócio
filtros:
  centro: 102
  qtde_minima: 3
  categoria: "VAREJO"

# Caminhos para salvar os produtos finais no DBFS
caminhos_saida:
  regras_associacao: /mnt/datalake/gold/recomendacoes/regras_associacao_puras
  lista_marketing: /mnt/datalake/gold/recomendacoes/lista_marketing_emails
  kpis_power_bi: /mnt/datalake/gold/recomendacoes/kpis_compra_casada
  kpis_geograficos: /mnt/datalake/gold/recomendacoes/kpis_por_bairro # Novo
  kpis_temporais: /mnt/datalake/gold/recomendacoes/kpis_por_mes      # Novo 