tabelas:
  faturamento: bol.faturamento_centros_bol
  produtos: bol.produtos_site

modelo_ia:
  min_support: 0.001
  min_confidence: 0.05

filtros:
  centro: 102
  qtde_minima: 3
  categoria: "VAREJO"

caminho_saida: /mnt/datalake/silver/benchmarking/basket_analysis_report 